import 'package:wallet_monitor/src/db/index.db.dart';
import 'package:wallet_monitor/src/db/models/currency.model.dart';

final List<Map<String, String>> currencies = [
  {"id": "1", "symbol": "Lek", "name": "AlbaniaLek"},
  {"id": "2", "symbol": "؋", "name": "AfghanistanAfghani"},
  {"id": "3", "symbol": "\$", "name": "ArgentinaPeso"},
  {"id": "4", "symbol": "ƒ", "name": "ArubaGuilder"},
  {"id": "5", "symbol": "\$", "name": "AustraliaDollar"},
  {"id": "6", "symbol": "₼", "name": "AzerbaijanManat"},
  {"id": "7", "symbol": "\$", "name": "BahamasDollar"},
  {"id": "8", "symbol": "\$", "name": "BarbadosDollar"},
  {"id": "9", "symbol": "Br", "name": "BelarusRuble"},
  {"id": "10", "symbol": "BZ\$", "name": "BelizeDollar"},
  {"id": "11", "symbol": "\$", "name": "BermudaDollar"},
  {"id": "12", "symbol": "\$b", "name": "BoliviaBoliviano"},
  {"id": "13", "symbol": "KM", "name": "BosniaAndHerzegovinaConvertibleMark"},
  {"id": "14", "symbol": "P", "name": "BotswanaPula"},
  {"id": "15", "symbol": "лв", "name": "BulgariaLev"},
  {"id": "16", "symbol": "R\$", "name": "BrazilReal"},
  {"id": "17", "symbol": "\$", "name": "BruneiDarussalamDollar"},
  {"id": "18", "symbol": "៛", "name": "CambodiaRiel"},
  {"id": "19", "symbol": "\$", "name": "CanadaDollar"},
  {"id": "20", "symbol": "\$", "name": "CaymanIslandsDollar"},
  {"id": "21", "symbol": "\$", "name": "ChilePeso"},
  {"id": "22", "symbol": "¥", "name": "ChinaYuanRenminbi"},
  {"id": "23", "symbol": "\$", "name": "ColombiaPeso"},
  {"id": "24", "symbol": "₡", "name": "CostaRicaColon"},
  {"id": "25", "symbol": "kn", "name": "CroatiaKuna"},
  {"id": "26", "symbol": "₱", "name": "CubaPeso"},
  {"id": "27", "symbol": "Kč", "name": "CzechRepublicKoruna"},
  {"id": "28", "symbol": "kr", "name": "DenmarkKrone"},
  {"id": "29", "symbol": "DR\$", "name": "DominicanRepublicPeso"},
  {"id": "30", "symbol": "\$", "name": "EastCaribbeanDollar"},
  {"id": "31", "symbol": "£", "name": "EgyptPound"},
  {"id": "32", "symbol": "\$", "name": "ElSalvadorColon"},
  {"id": "33", "symbol": "̄€", "name": "EuroMemberCountries"},
  {"id": "34", "symbol": "£", "name": "FalklandIslandsMalvinasPound"},
  {"id": "35", "symbol": "\$", "name": "FijiDollar"},
  {"id": "36", "symbol": "¢", "name": "GhanaCedi"},
  {"id": "37", "symbol": "£", "name": "GibraltarPound"},
  {"id": "38", "symbol": "Q", "name": "GuatemalaQuetzal"},
  {"id": "39", "symbol": "£", "name": "GuernseyPound"},
  {"id": "40", "symbol": "\$", "name": "GuyanaDollar"},
  {"id": "41", "symbol": "L", "name": "HondurasLempira"},
  {"id": "42", "symbol": "\$", "name": "HongKongDollar"},
  {"id": "43", "symbol": "Ft", "name": "HungaryForint"},
  {"id": "44", "symbol": "kr", "name": "IcelandKrona"},
  {"id": "45", "symbol": "₹", "name": "IndiaRupee"},
  {"id": "46", "symbol": "Rp", "name": "IndonesiaRupiah"},
  {"id": "47", "symbol": "﷼", "name": "IranRial"},
  {"id": "48", "symbol": "£", "name": "IsleOfManPound"},
  {"id": "49", "symbol": "₪", "name": "IsraelShekel"},
  {"id": "50", "symbol": "J\$", "name": "JamaicaDollar"},
  {"id": "51", "symbol": "¥", "name": "JapanYen"},
  {"id": "52", "symbol": "£", "name": "JerseyPound"},
  {"id": "53", "symbol": "лв", "name": "KazakhstanTenge"},
  {"id": "54", "symbol": "₩", "name": "KoreaNorthWon"},
  {"id": "55", "symbol": "₩", "name": "KoreaSouthWon"},
  {"id": "56", "symbol": "лв", "name": "KyrgyzstanSom"},
  {"id": "57", "symbol": "₭", "name": "LaosKip"},
  {"id": "58", "symbol": "£", "name": "LebanonPound"},
  {"id": "59", "symbol": "\$", "name": "LiberiaDollar"},
  {"id": "60", "symbol": "ден", "name": "MacedoniaDenar"},
  {"id": "61", "symbol": "RM", "name": "MalaysiaRinggit"},
  {"id": "62", "symbol": "₹", "name": "MauritiusRupee"},
  {"id": "63", "symbol": "\$", "name": "MexicoPeso"},
  {"id": "64", "symbol": "₮", "name": "MongoliaTughrik"},
  {"id": "65", "symbol": "MT", "name": "MozambiqueMetical"},
  {"id": "66", "symbol": "\$", "name": "NamibiaDollar"},
  {"id": "67", "symbol": "₹", "name": "NepalRupee"},
  {"id": "68", "symbol": "ƒ", "name": "NetherlandsAntillesGuilder"},
  {"id": "69", "symbol": "\$", "name": "NewZealandDollar"},
  {"id": "70", "symbol": "C\$", "name": "NicaraguaCordoba"},
  {"id": "71", "symbol": "₦", "name": "NigeriaNaira"},
  {"id": "72", "symbol": "kr", "name": "NorwayKrone"},
  {"id": "73", "symbol": "﷼", "name": "OmanRial"},
  {"id": "74", "symbol": "₹", "name": "PakistanRupee"},
  {"id": "75", "symbol": "B/.", "name": "PanamaBalboa"},
  {"id": "76", "symbol": "Gs", "name": "ParaguayGuarani"},
  {"id": "77", "symbol": "S/.", "name": "PeruSol"},
  {"id": "78", "symbol": "₱", "name": "PhilippinesPeso"},
  {"id": "79", "symbol": "zł", "name": "PolandZloty"},
  {"id": "80", "symbol": "﷼", "name": "QatarRiyal"},
  {"id": "81", "symbol": "lei", "name": "RomaniaLeu"},
  {"id": "82", "symbol": "₽", "name": "RussiaRuble"},
  {"id": "83", "symbol": "£", "name": "SaintHelenaPound"},
  {"id": "84", "symbol": "﷼", "name": "SaudiArabiaRiyal"},
  {"id": "85", "symbol": "Дин.", "name": "SerbiaDinar"},
  {"id": "86", "symbol": "₹", "name": "SeychellesRupee"},
  {"id": "87", "symbol": "\$", "name": "SingaporeDollar"},
  {"id": "88", "symbol": "\$", "name": "SolomonIslandsDollar"},
  {"id": "89", "symbol": "S", "name": "SomaliaShilling"},
  {"id": "90", "symbol": "R", "name": "SouthAfricaRand"},
  {"id": "91", "symbol": "₹", "name": "SriLankaRupee"},
  {"id": "92", "symbol": "Kr", "name": "SwedenKrona"},
  {"id": "93", "symbol": "CHF", "name": "SwitzerlandFranc"},
  {"id": "94", "symbol": "\$", "name": "SurinameDollar"},
  {"id": "95", "symbol": "£", "name": "SyriaPound"},
  {"id": "96", "symbol": "NT\$", "name": "TaiwanNewDollar"},
  {"id": "97", "symbol": "฿", "name": "ThailandBaht"},
  {"id": "98", "symbol": "TT\$", "name": "TrinidadAndTobagoDollar"},
  {"id": "99", "symbol": "₺", "name": "TurkeyLira"},
  {"id": "100", "symbol": "\$", "name": "TuvaluDollar"},
  {"id": "101", "symbol": "₴", "name": "UkraineHryvnia"},
  {"id": "102", "symbol": "£", "name": "UnitedKingdomPound"},
  {"id": "103", "symbol": "\$", "name": "UnitedStatesDollar"},
  {"id": "104", "symbol": "\$U", "name": "UruguayPeso"},
  {"id": "105", "symbol": "лв", "name": "UzbekistanSom"},
  {"id": "106", "symbol": "Bs", "name": "VenezuelaBolivar"},
  {"id": "107", "symbol": "₫", "name": "VietnamDong"},
  {"id": "108", "symbol": "﷼", "name": "YemenRial"},
  {"id": "109", "symbol": "Z\$", "name": "ZimbabweDollar"},
];

Future<void> insertsAllCurrencies() async {
  final db = DataBase.db;

  await db.writeTxn(() async {
    int size = await db.currencies.getSize();

    if (size == 0) {
      final length = currencies.length;
      for (int i = 0; i < length; i++) {
        await db.currencies.put(Currency(
          name: currencies[i]["name"]!,
          symbol: currencies[i]["symbol"]!,
        ));
      }
    }
  });
}

Future<void> _inserts(Isar db) async {
  currencies.map((currency) async => await db.currencies.put(Currency(
        id: int.parse(currency["id"]!),
        name: currency["name"]!,
        symbol: currency["symbol"]!,
      )));
}
